services:
  yt-dlp-redirect:
    image: yt-dlp-redirect:latest
    build: .
    pull_policy: build
    ports:
      - 3000:3000
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:3000'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2s
    restart: unless-stopped
